name: Portable Build

on: push

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: install frontend dependencies
        run: yarn install # change this to npm or pnpm depending on which one you use
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        with:
          tagName: "v__VERSION__"
          releaseName: "Sophosia v__VERSION__"
      - name: rename .exe file
        id: rename
        if: matrix.platform == 'windows-latest'
        run: |
          ref=${{github.ref}}
          version=${ref#refs/heads/HuntFeng/}
          name=Sophosia_${version}_portable.exe
          echo "name=$name" >> $GITHUB_OUTPUT
          mv "src-tauri/target/release/Sophosia.exe" $name
        shell: bash
      - uses: actions/upload-artifact@v4
        if: matrix.platform == 'windows-latest'
        with:
          name: ${{ steps.rename.outputs.name }}
          path: ${{ steps.rename.outputs.name }}
